#!/usr/bin/env ruby
# coding: utf-8

require 'yaml'

holidays_detailed = YAML.load_file('./holiday_jp/holidays_detailed.yml')
holidays = holidays_detailed.map {|k, v| v }.sort_by {|v| v['date'] }
outputPath = File.join('./Sources/HolidayJp/Holidays.generated.swift')

File.open(outputPath, 'w') do |io|
  io.write "//\n"
  io.write "//  Holidays.generated.swift\n"
  io.write "//  holiday_jp-swift\n"
  io.write "//\n"
  io.write "//  Generated by scripts/generate.rb\n"
  io.write "//\n"
  io.write "\n"
  io.write "let Holidays: [String: Holiday] = {\n"
  io.write "    var holidays: [String: Holiday] = [:]\n"
  io.write "    \n"

  holidays.each do |holiday|
    io.write %Q|    holidays["#{holiday['date']}"] = Holiday(|
    io.write %Q|ymd: "#{holiday['date']}",|
    io.write %Q|week: "#{holiday['week']}",|
    io.write %Q|weekEn: "#{holiday['week_en']}",|
    io.write %Q|name: "#{holiday['name']}",|
    io.write %Q|nameEn: "#{holiday['name_en']}"|
    io.write %Q|)\n|
  end

  io.write "    \n"
  io.write "    return holidays\n"
  io.write "}()\n"
end
