name: Test
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
