name: Test
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14
            swift-version: 5
          - os: macos-15
            swift-version: 6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@682457186b71c25a884c45c06f859febbe259240 # v2.3.0
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
